For lessons 04 write recipe and 05 write diagnostics
ACCESS-NRI/CMIP7_MED_Hackathon pull request #1
Opened 2024-07-29 02:36 UTC by flicj191

# Pull Request checklist

## Tasks

- [ ] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [ ] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

2024-07-30 06:31 UTC, flicj191 commented
@rbeucher  
i've pulled `gh-pages` into this to link to vscode setup page. Main changes from original were: 
- editing the example recipes in 'write your recipe' to use an ACCESS model
- loading xp65 module
- adding reference paths to cloned CMIP7-Hackathon folder - which has a branch called `exercise_example_files` where I've added some files
- added optional step in diagnostics lesson to copy the files to their folder for editing

2024-07-31 03:51 UTC, rbeucher requested changes
I have a few suggestions. See above. Good work!!

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +created in your working directory, this is a clone of the ESMValTool repository.
```suggestion
A clone of the ESMValTool repository should be available in your user folder in the `nf33`
`scratch` folder (`/scratch/nf33/$USER/ESMValTool`). If not, please make sure to run the
`check_hackathon` command after loading the `esmvaltool` module.
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
>  - *~/ESMValTool/esmvaltool/diag_scripts/examples/diagnostic.py*
```suggestion
```
ESMValTool/esmvaltool/recipes/examples/recipe_python.yml
ESMValTool/esmvaltool/diag_scripts/examples/diagnostic.py
```
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +>> - */scratch/.../Exercise3_files/diagnostic.py*
```suggestion
>```
>/scratch/nf33/$USER/Exercise3_files/recipe_python.yml
>/scratch/nf33/$USER/Exercise3_files/diagnostic.py
>```
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +>>       script: /scratch/.../Exercise3_files/diagnostic.py
```suggestion
>>       script: /scratch/nf33/$USER/Exercise3_files/diagnostic.py
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +>> esmvaltool run /scratch/.../Exercise3_files/recipe_python.yml
```suggestion
>> esmvaltool run /scratch/nf33/$USER/Exercise3_files/recipe_python.yml
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +>>       script: <path_to_script>/diagnostic.py
```suggestion
>>       script: <path_to_script diagnostic.py>
```

2024-07-31 03:51 UTC, rbeucher commented on _episodes/05-writingdiagnostics.md
> +       script: <path_to_script>/diagnostic.py
```suggestion
       script: <path_to_script diagnostic.py>
```

2024-07-31 03:51 UTC, rbeucher commented on files/recipe_warming_stripes_additional_datasets.yml
> +          - {dataset: ACCESS1-3, project: CMIP5, mip: Amon, exp: historical, ensemble: r1i1p1}
Can we do CMIP6 only?

2024-07-31 23:35 UTC, rbeucher approved these changes

2024-07-31 23:36 UTC, rbeucher commented
OK, I'm going to merge this for now. Might need some adjustments as we move forward.

2024-07-31 23:36 UTC, merged